### ISSUE TITLE
1

### ISSUE THREAD

**Issue by aqpmzngldh** [BeammNotFound/get-jobs-boss#2]

**Comment by aqpmzngldh** [comment]
> _No description provided._

我用的是125.0.6422.61，然后卡在这里了09:54:58.337 [main] INFO ResumeSubmission - 等待登陆..应该是找不到这个就卡住了wait15s.until(ExpectedConditions.presenceOfElementLocated(By.className("resume-catalogue")));

**Comment by aqpmzngldh** [comment]
> > _No description provided._
> 
> 我用的是125.0.6422.61，然后卡在这里了09:54:58.337 [main] INFO ResumeSubmission - 等待登陆..应该是找不到这个就卡住了wait15s.until(ExpectedConditions.presenceOfElementLocated(By.className("resume-catalogue")));

我重新找了个nav-school-new，然后替换就好了

**Comment by aqpmzngldh** [comment]
正在投递，然后突然出错：
14:45:28.734 [main] INFO ResumeSubmission - 投递南京迈特望 | 对日JAVA（双休） 11-14K一职
14:45:32.833 [main] INFO ResumeSubmission - 投递济南聚仁 | java开发工程师 8-13K一职
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at ResumeSubmission.resumeSubmission(ResumeSubmission.java:80)
	at ResumeSubmission.main(ResumeSubmission.java:39)
Disconnected from the target VM, address: '127.0.0.1:65405', transport: 'socket'

Process finished with exit code 1

**Comment by aqpmzngldh** [comment]
> 正在投递，然后突然出错： 14:45:28.734 [main] INFO ResumeSubmission - 投递南京迈特望 | 对日JAVA（双休） 11-14K一职 14:45:32.833 [main] INFO ResumeSubmission - 投递济南聚仁 | java开发工程师 8-13K一职 Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 at java.util.ArrayList.rangeCheck(ArrayList.java:659) at java.util.ArrayList.get(ArrayList.java:435) at ResumeSubmission.resumeSubmission(ResumeSubmission.java:80) at ResumeSubmission.main(ResumeSubmission.java:39) Disconnected from the target VM, address: '127.0.0.1:65405', transport: 'socket'
> 
> Process finished with exit code 1

经过检查，是因为有些的链接不可达
![2024-05-19_144951](https://github.com/BeammNotFound/get-jobs-boss/assets/124235388/9a46b5aa-06da-4300-b820-c21d3cb24882)

**Comment by aqpmzngldh** [comment]
> 正在投递，然后突然出错： 14:45:28.734 [main] INFO ResumeSubmission - 投递南京迈特望 | 对日JAVA（双休） 11-14K一职 14:45:32.833 [main] INFO ResumeSubmission - 投递济南聚仁 | java开发工程师 8-13K一职 Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 at java.util.ArrayList.rangeCheck(ArrayList.java:659) at java.util.ArrayList.get(ArrayList.java:435) at ResumeSubmission.resumeSubmission(ResumeSubmission.java:80) at ResumeSubmission.main(ResumeSubmission.java:39) Disconnected from the target VM, address: '127.0.0.1:65405', transport: 'socket'
> 
> Process finished with exit code 1

经检查，是因为某些的链接不可达，但是还是添加到了list中，所以找不到，上面那个a的href我看是正常的，要么跳过，要么就用上面那个就好咯
![2024-05-19_144951](https://github.com/BeammNotFound/get-jobs-boss/assets/124235388/872260ef-9e3d-4bb1-b572-78df065c05b3)
